name: Hadolint - Dockerfile linting
on:
  workflow_dispatch:  
  pull_request:
    types: [opened, synchronize]
    paths:
      - "Dockerfile"
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          verbose: true
